version: '3.8'

services:
  torch:
    restart: always
    environment:
      TORCH_PORT: 30080
    expose:
      - 30080
    image: public.ecr.aws/q9a8w4y6/my-torch:rasp
    network_mode: host

  web:
    restart: always
    ports:
      -  "38080:3000" # external 38080
    image: min1925k/nodejs_service:0.2
    network_mode: host
