version: "3.8"

services:
  nginx_api_gateway:
    build: .
    restart: always
    ports:
      - "38081:8080/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"


    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

