FROM node:18

WORKDIR /torchApp

COPY . .

RUN apt update && apt upgrade
RUN apt install -y python3 python3-pip libgl1-mesa-glx
RUN pip install numpy timm opencv-python pillow six

RUN pip install torch
RUN pip install torchvision

RUN npm install

CMD ["node", "index.js"]