apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-torch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-torch
  template:
    metadata:
      labels:
        app: nodejs-torch
    spec:
      hostname: nodejs-torch
      containers:
      - name: torch
        image: public.ecr.aws/q9a8w4y6/my-torch
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 30080
      - name: web
        image: public.ecr.aws/q9a8w4y6/my-nodejs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-torch-service
spec:
  selector:
    app: nodejs-torch
  ports:
  - nodePort: 32649 # 클러스터 외부에서 접속하는 포트 -> targetPort
    port: 38080 # 클러스터 내부에서 이 서비스로 접속할 수 있는 포트
    protocol: TCP
    targetPort: 3000
  type: NodePort